"""Markdown report generation."""
from __future__ import annotations

from collections import Counter
from datetime import datetime
from pathlib import Path

from .models import OperationResult


def emit_markdown(op: OperationResult, out_dir: Path | None = None) -> Path:
    out_dir = Path(out_dir) if out_dir else op.target_root
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = op.finished_at.strftime("%Y%m%d_%H%M%S")
    path = out_dir / f"FolderAngel_Report_{stamp}.md"
    path.write_text(_build(op), encoding="utf-8")
    return path


def _build(op: OperationResult) -> str:
    lines: list[str] = []
    lines.append(f"# FolderAngel Report — {op.target_root}")
    lines.append("")
    lines.append(f"- 실행 시각: {op.started_at.isoformat(timespec='seconds')} → {op.finished_at.isoformat(timespec='seconds')}")
    dur = (op.finished_at - op.started_at).total_seconds()
    lines.append(f"- 소요: {dur:.1f} 초")
    lines.append(f"- 모드: {'Dry-Run (변경 없음)' if op.dry_run else '실행'}")
    lines.append(f"- 스캔: {op.total_scanned}개 / 이동: {op.total_moved}개 / 바로가기: {op.total_shortcuts}개 / 스킵: {op.total_skipped}개")
    if op.operation_id is not None:
        lines.append(f"- 오퍼레이션 ID: {op.operation_id}")
    lines.append("")

    # Category distribution
    counter = Counter(m.category_id for m in op.moved)
    lines.append("## 카테고리 분포")
    lines.append("")
    lines.append("| 카테고리 | 폴더명 | 파일 수 |")
    lines.append("| --- | --- | ---: |")
    for cat in op.categories:
        n = counter.get(cat.id, 0)
        lines.append(f"| `{cat.id}` | {cat.name} | {n} |")
    lines.append("")

    lines.append("## 이동 목록")
    lines.append("")
    if op.moved:
        lines.append("| 카테고리 | 새 경로 | 원본 경로 | 사유 | 점수 |")
        lines.append("| --- | --- | --- | --- | ---: |")
        for mf in op.moved[:500]:
            lines.append(
                f"| {mf.category_id} | `{mf.new_path}` | `{mf.original_path}` | {mf.reason or '-'} | {mf.score:.2f} |"
            )
        if len(op.moved) > 500:
            lines.append(f"| … | (+{len(op.moved) - 500} more) | | | |")
    else:
        lines.append("_이동된 파일이 없습니다._")
    lines.append("")

    shortcut_lines = [mf for mf in op.moved if mf.shortcuts]
    if shortcut_lines:
        lines.append("## 바로가기")
        lines.append("")
        lines.append("| 대상 파일 | 바로가기 위치 |")
        lines.append("| --- | --- |")
        for mf in shortcut_lines[:500]:
            for sp in mf.shortcuts:
                lines.append(f"| `{mf.new_path}` | `{sp}` |")
        lines.append("")

    if op.skipped:
        lines.append("## 스킵된 파일")
        lines.append("")
        lines.append("| 경로 | 사유 |")
        lines.append("| --- | --- |")
        for sf in op.skipped[:500]:
            lines.append(f"| `{sf.path}` | {sf.reason} |")
        lines.append("")

    lines.append(f"_Generated by FolderAngel at {datetime.now().astimezone().isoformat(timespec='seconds')}_")
    return "\n".join(lines)
